### PR TITLE
Completed Project

### PR DESCRIPTION
**Pull request by sneufa**
Completed the project including markup, styling and positioning.

### CODE REVIEW

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hello @sneufa 👋🏾 👋🏾 this is a really good job you did. I like the layout of the page, it looks almost like the original page, keep it up. However, before marking the project as complete, let's make a few adjustments

- [ ] You are missing this image in the theory of inflation section

image

- [ ] You are missing the for Editor's picks section on the righmost side. . ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

image

- [ ] Avoid mixing CSS styling with HTML code, this is reflected in `index.html ` move all styling to style.css

- [ ] Add the following sections in your README file. You can refer to this [template](https://github.com/microverseinc/readme-template)
- Getting Started
This is an example of how you may give instructions on setting up your project locally. Modify this file to match your project, remove sections that don't apply.
`To get a local copy up and running follow these simple example steps.`
- Authors
- :handshake: Contributing
- Show your support
- Acknowledgments
-  License

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help_
Regards
Peris Ndanu

**Comment by sneufa** [comment]
Hello @mimipeshy I have put a link of the original New York Times i.e. https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0 article in my README and there is no such image in the theory of inflation section. 

The styling I did in the HTML file is mostly related to fonts. I couldn't make the original font of New York Times work by putting it in style.css due to some CDN issues.

I'll update the README.

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @sneufa :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by sneufa** [comment]
Approved

**Pull request merged**
